# Generated by Django 3.2.7 on 2021-09-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_people_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(default='Adam_Smith@chapman.edu', max_length=254, unique=True),
        ),
    ]
