# Generated by Django 3.2.7 on 2021-09-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210903_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiments',
            options={'ordering': ['name'], 'verbose_name': 'Experiment', 'verbose_name_plural': 'Experiments'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'People', 'verbose_name_plural': 'People'},
        ),
    ]
