# Generated by Django 3.2.7 on 2021-09-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210903_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiments',
            old_name='address',
            new_name='url',
        ),
        migrations.AddField(
            model_name='experiments',
            name='available_to_all',
            field=models.BooleanField(default=False),
        ),
    ]
