# Generated by Django 3.2.7 on 2021-09-07 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210907_0507'),
        ('main', '0009_helpdocs'),
    ]

    operations = [
    ]
