# Generated by Django 3.2.7 on 2021-09-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_merge_0007_auto_20210907_0507_0009_helpdocs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='experiments',
            field=models.ManyToManyField(to='main.Experiments'),
        ),
    ]
