# Generated by Django 3.2.7 on 2021-09-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_profile_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='emailVerificationResetText',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='parameters',
            name='emailVerificationTextSubject',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='parameters',
            name='passwordResetText',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='parameters',
            name='passwordResetTextSubject',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
