# Generated by Django 3.2.7 on 2021-09-08 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210908_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameters',
            old_name='emailVerificationResetText',
            new_name='email_verification_reset_text',
        ),
        migrations.RenameField(
            model_name='parameters',
            old_name='emailVerificationTextSubject',
            new_name='email_verification_text_subject',
        ),
        migrations.RenameField(
            model_name='parameters',
            old_name='passwordResetText',
            new_name='password_reset_text',
        ),
        migrations.RenameField(
            model_name='parameters',
            old_name='passwordResetTextSubject',
            new_name='password_reset_text_subject',
        ),
    ]
