# Generated by Django 3.2.7 on 2021-09-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210908_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_reset_key',
            field=models.UUIDField(blank=True, null=True, verbose_name='Password Reset Key'),
        ),
    ]
