# Generated by Django 3.2.7 on 2021-09-08 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_profile_password_reset_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameters',
            old_name='email_verification_reset_text',
            new_name='email_verification_text',
        ),
    ]
