# Generated by Django 3.2.7 on 2021-09-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_email_verification_reset_text_parameters_email_verification_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiments',
            name='name',
            field=models.CharField(default='*** New Experiment **', max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='site_URL',
            field=models.CharField(default='https://www.google.com', max_length=200),
        ),
    ]
