# Generated by Django 4.0.7 on 2022-08-11 19:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_frontpagenotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='email_verification_text',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='password_reset_text',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
