# Generated by Django 4.2.13 on 2024-05-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_profileloginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mfa_hash',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Multi-factor Hash'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mfa_required',
            field=models.BooleanField(default=False, verbose_name='Multi-factor Required'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mfa_setup_complete',
            field=models.BooleanField(default=False, verbose_name='Multi-factor Setup Complete'),
        ),
    ]
