# Generated by Django 4.2.13 on 2024-05-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_profile_mfa_hash_profile_mfa_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='Disabled'),
        ),
    ]
