# Generated by Django 5.2 on 2025-05-02 22:32

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_experiments_disabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileloginattempt',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Profile Login Attempt', 'verbose_name_plural': 'Profile Login Attempts'},
        ),
        migrations.AlterField(
            model_name='helpdocs',
            name='text',
            field=tinymce.models.HTMLField(default='', max_length=100000, verbose_name='Help Doc Text'),
        ),
    ]
