# Generated by Django 5.2 on 2025-05-02 22:45

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_profileloginattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontpagenotice',
            name='body_text',
            field=tinymce.models.HTMLField(default='', max_length=100000, verbose_name='Body Text'),
        ),
    ]
