# Generated by Django 5.2.11 on 2026-05-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_profile_options_alter_experiments_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='subject_time_zone',
            field=models.CharField(default='US/Pacific', max_length=1000),
        ),
    ]
